[project]
# please adapt to package name
name = "ghga_arcticfreeze"
version = "0.1.0"
description = "GHGA-Arcticfreeze - a short description"
dependencies = [
    "typer >= 0.25.1",
    "pydantic >= 2.13.0, <3",
    "immutabledict >= 4.3.1, <5",
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/ghga-arcticfreeze"

[project.scripts]
# please adapt to package name
ghga-arcticfreeze = "ghga_arcticfreeze.__main__:run"
