[project]
name = "ghga-arcticfreeze"
version = "1.0.0"
description = "Enjoy Python on the rocks with deeply (recursively) frozen data structures."
authors = [
    { name = "Kersten Henrik Breuer", email = "kersten-breuer@outlook.com" },
    { name = "The GHGA Authors", email = "contact@ghga.de" },
]
maintainers = [
    { name = "The GHGA Authors", email = "contact@ghga.de" },
]
dependencies = [
    "immutabledict >= 4.3.1, <5",
]

[project.optional-dependencies]
pydantic = [
    "pydantic >= 2.13.0, <3",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-arcticfreeze"
